[build]
  publish = "."
  command = "echo 'Node.js version:' && node --version && echo 'Static files ready for deployment.'"

[dev]
  framework = "#static"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[functions]
  directory = "functions"

# Set Node.js version
[build.environment]
  NODE_VERSION = "16.19.0"