[build]
  publish = "."
  command = "chmod +x ./build.sh && ./build.sh"

[dev]
  framework = "#static"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[functions]
  directory = "functions"

# Set Node.js version
[build.environment]
  NODE_VERSION = "18"