[build]
  publish = "."
  command = "echo 'No build command required'"

[dev]
  framework = "#static"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[functions]
  directory = "functions"

# For Netlify DB (NEON) integration
[build.environment]
  NODE_VERSION = "18"